### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.security.core.context.SecurityContextImpl

### ISSUE THREAD

**Issue by songyunlu** [aws/aws-dynamodb-session-tomcat#1]
Hi:

I have added **AmazonDynamoDBSessionManagerForTomcat-1.0.0.jar** to the *lib* directory of my Tomcat installation and tried to store session in DynamoDB. Howerver when DynamoDBSessionManager tries to load sessions from dynamodb, it throws **java.lang.ClassNotFoundException:org.springframework.security.core.context.SecurityContextImpl**. 

Since I use Spring Security for authentication stuff. It seems that the session manager cannot deserialize the session value to the SecurityContextImpl because it cannot find the classes.

I have tried to add the dependencies (Spring Security) to the *lib* directory of the Tomcat installation, but in the end, I got the same exception with classes of  my domain object.

Should I put all classes of my domain object into the *lib* directory? or Is there any intuitive way to solve this problem? thx.

**Comment by wyangnz** [comment]
Hi fulghum,
We have Liferay 6.1 CE with Tomcat bundle runs on AWS EC2. The DBSessionManager does not work.  It shows "java.lang.ClassNotFoundException: com.liferay.portal.servlet.PortalSessionActivationListener" and other classes in liferay. In the Liferay/Tomcat bundle, the Liferay portal is under [tomcat-home]/webapps/ROOT and there is file [tomcat-home]/conf/Catalina/localhost/ROOT.xml which is almost empty. It appears the classLoader for the webapp cannot load class in webapps/ROOT/ path. 
I made small changes on DynamoDBSessionStore as follows, it works but I am not sure if there is a better solution.

        CustomObjectInputStream objectInputStream = null;
        ObjectInputStream objectInputStream2 = null;
        try {
            Container webapp = getManager().getContainer();
            objectInputStream = new CustomObjectInputStream(inputStream, webapp.getLoader().getClassLoader());
            readObject = objectInputStream.readObject();
        }    catch(java.lang.ClassNotFoundException e) { 
        	objectInputStream2 = new ObjectInputStream(inputStream);
        	readObject = objectInputStream2.readObject();
        } finally {
            try { 
            	if(objectInputStream != null) {
            		objectInputStream.close(); 
            	} 
            	if (objectInputStream2 != null){
            		objectInputStream2.close();
            	}
            }catch (Exception e){}
        }

Thanks in advance for any suggestion.

Weimin
