### ISSUE TITLE
Stale Session Data

### ISSUE THREAD

**Issue by drei01** [aws/aws-dynamodb-session-tomcat#18]
We have been testing the dynamodb session manager in our elasticbeanstalk (java 7 tomcat 7) environment. We noticed issues with stale session data being returned in an app that uses the session to store the user. Intermittently, the user would switch back to a previous one from that session. When this happens, the data in dynamodb is clearly out of date with what should be on the session, but for some reason it is loaded from dynamodb rather than using the session in memory.

After debugging through the code, we haven't managed to pinpoint the issue but it does not happen when using the JDBCStore that comes bundled with tomcat.

**Comment by Selindek** [comment]
I've experienced the same issue. It seems that the session-manager loads back the old session-data from the DB instead of storing the new one when the session data has changed in memory.

**Comment by Selindek** [comment]
I've found the problem and fixed it. I will do a pull-request soon.
Actually it's a very serious issue. I don't recommend using the manager to anybody until the fix!

**Comment by shorea** [comment]
Resolved in latest release
