### ISSUE TITLE
Using DynamoDB for Tomcat sessions api via http proxy

### ISSUE THREAD

**Issue by geekpete** [aws/aws-dynamodb-session-tomcat#2]
Hi,

If using a http proxy to get to the AWS APIs from within a private VPC, have you tested this session manager via an http proxy?

We've encountered errors in this scenario.

Are most people using a transparent NAT to hit AWS APIs external to the private VPC network such as Dynamo?

Would the overhead of using an HTTP proxy for something like session storage outweigh some of the speed benefits of Dynamo/Redis AWS services?

**Comment by fulghum** [comment]
Thanks @avandendaele
