### ISSUE TITLE
SessionManager and Server Hot Swaps

### ISSUE THREAD

**Issue by octavianlaies** [aws/aws-dynamodb-session-tomcat#21]
Hi,

I was looking over the implementation of this session manager and I have a question. Here's how I understand it's working:
The sessions are flushed to DynamoDB in 2 cases: when tomcat is stopped and 30 seconds after the session turns idle (configurable).

So here's my situation: I have an instance in ELB with sticky sessions that I want to take out of traffic. I have connection draining to ensure active connections complete however due to the 30 second flush interval if I take the instance out of traffic (but not stop it) I will loose all sessions that have been active within the last 30 seconds. Is there a way around this? To me it looks like this is not possible with this session manager. Even if I set the flush to 1 seconds, I can still loose sessions.

Thank you

**Comment by shorea** [comment]
Not sure how I missed this and the answer probably won't help you now but Tomcat will attempt to unload sessions on a clean shutdown to the persistent store.
