### ISSUE TITLE
Can't use an undefined value as a HASH reference at DynamoDB.pm line 1544

### ISSUE THREAD

**Issue by md-qa** [aws/aws-dynamodb-session-tomcat#22]
Getting this error while connecting to Dynamo DB through perl script. Any pointers to reason and resolution for this error will  help.  Following link discusses same issue - https://github.com/ukautz/Net-Amazon-DynamoDB/issues/1 . However, not sure how to implement the resolution in perl script

**Comment by shorea** [comment]
@md-qa can you open an issue in https://github.com/ukautz/Net-Amazon-DynamoDB. This repo is for a DynamoDB backed session manager for Tomcat.
