### ISSUE TITLE
How do you specify Configuration?

### ISSUE THREAD

**Issue by gregpassmore** [aws/aws-dynamodb-session-tomcat#28]
For example, tableName. I am using a .ebextensions file to set this up in the context.xml. I would prefer to do all config at runtime, so I can load config from a remote resource. How do I do this?

**Comment by shorea** [comment]
Sorry for the long silence. It's possible to get an instance of DynamoDBSessionManager at runtime via getContext().getManager() or getContext().getContainer().getManager(). We expose setters for our different configurable options but unfortunately these are only read once at initialization time so you would need to obtain an instance of the Manager after it was created but before it was initialized to achieve what you want and I doubt that will be easy (or possible) to do. I don't particularly like the idea of making the configuration hot swappable, i.e. modifiable at runtime after it's already been initialized. Would it be possible to write a wrapper around your tomcat startup script that pulls this remote resource and dynamically edits your context.xml with the appropriate configuration?
