### ISSUE TITLE
If model in session throws NotSerializableException - do not store in DynamoDB

### ISSUE THREAD

**Issue by AlexKovalevich** [aws/aws-dynamodb-session-tomcat#30]
I've just had a look at that DynamoSessionItem by (new String(sessionItem.sessionData.array())) in debugger. It shows that session data already contains model with stacktrace for NotSerializableException . I think such behavior should be changed. As long as you've managed to add such a session into DynamoDB   - you're done until it expires or manually cleaned.

**Comment by AlexKovalevich** [comment]
sessionItem dump:

�� sr java.lang.Long;��̏#� J valuexr java.lang.Number������  xp  Ocx�2sq ~    Oczg�sr java.lang.Integer⠤���8 I valuexq ~   sr java.lang.Boolean� r�՜�� Z valuexp sq ~ sq ~    Oczg�t  5D8BF46517BF1B4399B34B5A5B7698EBsq ~    t 9___DealSalesCartInterceptor_totalDealsInCart_sessionKey__sq ~          t viewDealsFormWrappersr 2com.avk.gtd.web.uiModel.SessionAttributeBeanHolder륤d":�� L beant Ljava/lang/Object;L 
propertiest Ljava/util/Map;xpsr 9com.avk.gtd.web.business.deal.ViewBusinessDealsFilterForm�����H Z currentOrderAscendingI 
pageNumberI recordsPerPageL filterPosIdt Ljava/util/Set;L lifecycleStatusesq ~ L orderByt Ljava/lang/String;L publishStatusesq ~ xp       
sr java.util.LinkedHashSet�l�Z��*  xr java.util.HashSet�D�����4  xpw   ?@     sq ~         sq ~         sq ~         sq ~         xsq ~ w   ?@     ~r Bcom.avk.gtd.common.services.model.DealServiceModel$LifecycleStatus          xr java.lang.Enum          xpt NEW~q ~ t 	PUBLISHED~q ~ t 	COMPLETED~q ~ t 
TERMINATEDxt LIFECYCLE_STATUS_ASCsq ~ w   ?@     ~r @com.avk.gtd.common.services.model.DealServiceModel$PublishStatus          xq ~  t SYNCHRONIZED~q ~ +t DIRTYxsr java.util.HashMap���`� F 
loadFactorI 	thresholdxp?@      w       xt Oorg.springframework.security.web.csrf.HttpSessionCsrfTokenRepository.CSRF_TOKENsr 6org.springframework.security.web.csrf.DefaultCsrfTokenZ��/��� L 
headerNameq ~ L 
parameterNameq ~ L tokenq ~ xpt X-CSRF-TOKENt _csrft $71aae41c-cb16-40fd-8c0d-cfe62c30876bt 5___UserContextInterceptor_userContextModelInSession__sr *com.avk.gtd.web.uiModel.GeoLocationUIModel���TP��b I radiusZ 
radiusDefaultL coordinatest #Lcom/vividsolutions/jts/geom/Point;L 
geoCountryt +Lcom/avk/gtd/web/uiModel/GeoCountryUIModel;L geoPlacet )Lcom/avk/gtd/web/uiModel/GeoPlaceUIModel;L 	updatedByt 6Lcom/avk/gtd/web/uiModel/GeoLocationUIModel$UpdatedBy;xp  �Psr !com.vividsolutions.jts.geom.PointD{��* L coordinatest 0Lcom/vividsolutions/jts/geom/CoordinateSequence;xr $com.vividsolutions.jts.geom.Geometryy��e"�J> I SRIDL envelopet &Lcom/vividsolutions/jts/geom/Envelope;L factoryt -Lcom/vividsolutions/jts/geom/GeometryFactory;L userDataq ~ xp  �psr +com.vividsolutions.jts.geom.GeometryFactory�X�߮L� I SRIDL coordinateSequenceFactoryt 7Lcom/vividsolutions/jts/geom/CoordinateSequenceFactory;L precisionModelt ,Lcom/vividsolutions/jts/geom/PrecisionModel;xp    {sr  java.io.NotSerializableException(Vx �5  xr java.io.ObjectStreamExceptiond��k�9��  xr java.io.IOExceptionl�sde%�  xr java.lang.Exception��>;�  xr java.lang.Throwable��5'9w�� L causet Ljava/lang/Throwable;L 
detailMessaget Ljava/lang/String;[ 
stackTracet [Ljava/lang/StackTraceElement;L suppressedExceptionst Ljava/util/List;xpq ~ 	t <org.geolatte.geom.jts.PointSequenceCoordinateSequenceFactoryur [Ljava.lang.StackTraceElement;F*<<�"9  xp   !sr java.lang.StackTraceElementa	Ś&6݅ I 
lineNumberL declaringClassq ~ L fileNameq ~ L 
methodNameq ~ xp  �t java.io.ObjectOutputStreamt ObjectOutputStream.javat writeObject0sq ~ 
  q ~ q ~ t defaultWriteFieldssq ~ 
  �q ~ q ~ t writeSerialDatasq ~ 
  �q ~ q ~ t writeOrdinaryObjectsq ~ 
  �q ~ q ~ q ~ sq ~ 
  q ~ q ~ q ~ sq ~ 
  �q ~ q ~ q ~ sq ~ 
  �q ~ q ~ q ~ sq ~ 
  �q ~ q ~ q ~ sq ~ 
  q ~ q ~ q ~ sq ~ 
  �q ~ q ~ q ~ sq ~ 
  �q ~ q ~ q ~ sq ~ 
  �q ~ q ~ q ~ sq ~ 
  \q ~ q ~ t writeObjectsq ~ 
  �t +org.apache.catalina.session.StandardSessiont StandardSession.javat 
doWriteObjectsq ~ 
  \q ~ $q ~ %t writeObjectDatasq ~ 
   #t zcom.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.converters.DefaultDynamoSessionItemConvertert &DefaultDynamoSessionItemConverter.javat 
toSessionItemsq ~ 
   %t icom.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.converters.SessionConvertert SessionConverter.javaq ~ ,sq ~ 
   :t bcom.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.DynamoSessionStoraget DynamoSessionStorage.javat saveSessionsq ~ 
   `t bcom.amazonaws.tomcatsessionmanager.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionStoret DynamoDBSessionStore.javat savesq ~ 
  2t 1org.apache.catalina.session.PersistentManagerBaset PersistentManagerBase.javat writeSessionsq ~ 
  q ~ 9q ~ :t swapOutsq ~ 
  uq ~ 9q ~ :t unloadsq ~ 
  bq ~ 9q ~ :t stopInternalsq ~ 
   �t &org.apache.catalina.util.LifecycleBaset LifecycleBase.javat stopsq ~ 
  t (org.apache.catalina.core.StandardContextt StandardContext.javaq ~ Asq ~ 
   �q ~ Cq ~ Dq ~ Esq ~ 
  �t 0org.apache.catalina.core.ContainerBase$StopChildt ContainerBase.javat callsq ~ 
  �q ~ Kq ~ Lq ~ Msq ~ 
  
t java.util.concurrent.FutureTaskt FutureTask.javat runsq ~ 
  vt 'java.util.concurrent.ThreadPoolExecutort ThreadPoolExecutor.javat 	runWorkersq ~ 
  it .java.util.concurrent.ThreadPoolExecutor$Workerq ~ Uq ~ Rsq ~ 
  �t java.lang.Threadt Thread.javaq ~ Rsr &java.util.Collections$UnmodifiableList�%1�� L listq ~ xr ,java.util.Collections$UnmodifiableCollectionB ��^� L ct Ljava/util/Collection;xpsr java.util.ArrayListx����a� I sizexp    w    xq ~ axt  ___NOT_SERIALIZABLE_EXCEPTION___t SPRING_SECURITY_CONTEXTsr =org.springframework.security.core.context.SecurityContextImpl      � L authenticationt 2Lorg/springframework/security/core/Authentication;xpsr Oorg.springframework.security.authentication.UsernamePasswordAuthenticationToken      � L credentialst Ljava/lang/Object;L 	principalq ~ xr Gorg.springframework.security.authentication.AbstractAuthenticationTokenӪ(~nGd Z 
authenticatedL authoritiest Ljava/util/Collection;L detailsq ~ xpsr &java.util.Collections$UnmodifiableList�%1�� L listt Ljava/util/List;xr ,java.util.Collections$UnmodifiableCollectionB ��^� L cq ~ xpsr java.util.ArrayListx����a� I sizexp    w    ~r *com.avk.gtd.common.security.PermissionType          xr java.lang.Enum          xpt ACCOUNT_CLIENT_READ_OWN~q ~ t ACCOUNT_CLIENT_UPDATE_OWN~q ~ t BUSINESS_ACCOUNT_READ_OWN~q ~ t BUSINESS_ACCOUNT_UPDATE_OWN~q ~ t BUSINESS_DEAL_CREATE_OWN~q ~ t BUSINESS_DEAL_DELETE_OWN~q ~ t BUSINESS_DEAL_LIST_OWN~q ~ t BUSINESS_DEAL_MANAGE_ALL_ANY~q ~ t BUSINESS_DEAL_PAUSE_OWN~q ~ t (BUSINESS_DEAL_PAYMENT_INVOICE_CREATE_OWN~q ~ t &BUSINESS_DEAL_PAYMENT_INVOICE_READ_OWN~q ~ t BUSINESS_DEAL_PUBLISH_OWN~q ~ t BUSINESS_DEAL_READ_OWN~q ~ t BUSINESS_DEAL_RESUME_OWN~q ~ t BUSINESS_DEAL_SALE_PROCESS_OWN~q ~ t BUSINESS_DEAL_SALE_READ_OWN~q ~ t BUSINESS_DEAL_UPDATE_OWN~q ~ t BUSINESS_SALES_POINT_CREATE_OWN~q ~ t BUSINESS_SALES_POINT_DELETE_OWN~q ~ t BUSINESS_SALES_POINT_LIST_OWN~q ~ t BUSINESS_SALES_POINT_READ_OWN~q ~ t BUSINESS_SALES_POINT_UPDATE_OWN~q ~ t CLIENT_DEAL_DETAILS_OWN~q ~ t CLIENT_DEAL_MANAGE_CART_OWN~q ~ t CLIENT_DEAL_REVIEW_CREATE_OWN~q ~ t CLIENT_DEAL_REVIEW_SEARCH_OWN~q ~ t CLIENT_DEAL_REVIEW_UPDATE_OWN~q ~ t CLIENT_DEAL_SEARCH_OWN~q ~ t PAYMENT_INVOICE_PAY_OWN~q ~ t PAYMENT_INVOICE_READ_OWN~r $com.avk.gtd.common.security.RoleType          xq ~ t BUSINESS_OWNER~q ~ Nt CLIENTxq ~ sr Horg.springframework.security.web.authentication.WebAuthenticationDetails      � L 
remoteAddresst Ljava/lang/String;L 	sessionIdq ~ Txpt 192.168.1.1t  FF31B71D20C788AFD0A0729A0750B01Epsr ,com.avk.gtd.common.security.UserDetailsModel�EZ��� L accountt ;Lcom/avk/gtd/common/services/model/VersionableModelWrapper;L 	firstNameq ~ TL lastNameq ~ TL 	loginNameq ~ Txr 2org.springframework.security.core.userdetails.User      � Z accountNonExpiredZ accountNonLockedZ credentialsNonExpiredZ enabledL authoritiest Ljava/util/Set;L passwordq ~ TL usernameq ~ Txpsr %java.util.Collections$UnmodifiableSet��я��U  xq ~ sr java.util.TreeSetݘP���[  xpsr Forg.springframework.security.core.userdetails.User$AuthorityComparator      �  xpw    q ~ q ~ q ~ q ~ q ~ q ~ q ~ q ~  q ~ "q ~ $q ~ &q ~ (q ~ *q ~ ,q ~ .q ~ 0q ~ 2q ~ 4q ~ 6q ~ 8q ~ :q ~ <q ~ >q ~ @q ~ Bq ~ Dq ~ Fq ~ Hq ~ Jq ~ Lq ~ Oq ~ Qxpt 1@asr 9com.avk.gtd.common.services.model.VersionableModelWrapper�N 4Ϙ� I versionxr 7com.avk.gtd.common.services.model.ManagableModelWrapper��l��i� J idL modelq ~ xp       sr .com.avk.gtd.common.services.model.AccountModel�'�:��� Z 	activatedD balanceZ blacklistedI emailComplaintsCountI emailRequestNumberI invalidAccessAttemptsZ lockedI statusL createdDatet Ljava/util/Date;L emailq ~ TL emailBlockedUntilq ~ hL emailDescriptionq ~ TL emailStatusCodet <Lcom/avk/gtd/common/services/model/AccountModel$EmailStatus;L 
expiryDateq ~ hL 	firstNameq ~ TL lastAccessDateq ~ hL lastEmailRequestDateq ~ hL lastModifiedDateq ~ hL lastNameq ~ TL lastPasswordResetRequestDateq ~ hL localet Ljava/util/Locale;L loginq ~ TL newEmailq ~ TL passwordq ~ TL rolesq ~ [xp                          sr java.sql.Timestamp&��S�e I nanosxr java.util.Datehj�KYt  xpw  Oa��x1�Ԁt 1@appppt First1sq ~ lw  Oa��(x�A�sq ~ lw  Oa�
Xx0��sq ~ lw  Oa�
Xx0ue@t Last1sq ~ lw  Oa��x1�Ԁsr java.util.Locale~�`�0�� I hashcodeL countryq ~ TL 
extensionsq ~ TL languageq ~ TL scriptq ~ TL variantq ~ Txp����t  q ~ xt enq ~ xq ~ xxq ~ cpt <$2a$10$elmhUXEMdn/zzxoK5PsvFeRlZ5X1KLTO7zFuNaRjsNPQ/dfpwDDs.sr java.util.HashSet�D�����4  xpw   ?@     q ~ Oq ~ Qx   q ~ pq ~ tq ~ c

**Comment by shorea** [comment]
Can you elaborate on what problem you're having? I'm having trouble reading the dump above.

**Comment by AlexKovalevich** [comment]
Sure, I can't imagine more exiting activity then reading dumps too :) Almost like in "The Matrix"!
Ok, now seriously, the issue is that my session had a not serializable object. Session manager tried to serialized it, of cause NotSerializableException poped up. At this point I'd expect session manager to complain to log file about this issue and ignore unserialazable object tree. But instead of ignoring, session manager managed to serialized NotSerializableException and all the long stack trace and put it into DynamoDB. 

The good thing here is that among different garbage the dump contains kind of human readable names of classes, so by looking through it we can get a general idea about object types and their sequence how they are stored in this session. If we search for "NotSerializableException" and start to look after we'd see that now session contains full stack trace with references to DynamoDB, Spring, Tomcat etc - all the system internal, something that should never be in session.

The reason why I attached the dump was to prove that DynamoDB now contains something that it shouldn't.

**Comment by AlexKovalevich** [comment]
Just imagine that one application has a bug where under very rare use case which wasn't captured by QA there is a not serializable object sneaks into session. What happens in production?:

Case 1)  when session manager would ignore such a session, user would see something like 500 error, would open a different page and it would work because session manager would load the latest valid session from DynamoDb. So user could continue doing other things.

Case 2) like in the bug. Session manager has persisted invalid session object. On the next request tomcat reads session from DynamoDB and it will never be deserialized again. Now user can't visit other pages, can't logout - nothing. Until session expires user can't continue working from the same browser. To make it worth, some sessions have very long expiration time because they are out of memory, some systems have functionality if you log in from a different http session it can check by UID and try to transfer existing session. Those user are doomed for a long time !

For safety I'd add two things:
1) don't persist session on "NotSerializableException"
2) if session can not be recovered - delete that object from DynamoDB (this should be configurable).

The way it works now it's a bit scary to use on production, as similar bug can prevent user from accessing entire web app.

**Comment by shorea** [comment]
Okay so here is what I found.

Standard session makes an attempt to deal with non-serializable attributes. writeObject (which we use to serialize the session data) skips any attributes which are outright not serializable. This is a very shallow check and only checks if the attribute object itself implements Serializable and doesn't assert on any other objects in the object graph. Any errors occurred during the actual serialization (using ObjectOutputStream) get handled a little differently. Here writeObject catches the NonSerializableException and writes a special String ("___NOT_SERIALIZABLE_EXCEPTION___") to the output stream to indicate the attribute was not able to be serialized. Now that would be fine as readObject has logic to ignore deserializing any attribute with that special string but unfortunately ObjectOutputStream and ObjectInputStream swoop in to ruin the day. When ObjectOutputStream encounters a non-serializable object it to writes a special indicator (TC_EXCEPTION) and the serialized exception object (which includes the stack trace). This is written internally before "___NOT_SERIALIZABLE_EXCEPTION___". Now when StandardSession.readObject goes to load the session data it uses ObjectInputStream which is explicitly checking for the TC_EXCEPTION indicator and if it is encountered it throws a WriteAbortedException wrapping the deserialized exception object. Because it fails fast the logic readObject has for skipping attributes that were serialized as "___NOT_SERIALIZABLE_EXCEPTION___" never gets executed and the session deserialization dies.

So for steps forward and to address your suggestions
1. I don't think we will be able to reliably detect if a session was persisted with non-serializable objects in the graph. Exceptions are only thrown when attempting to read the written data. We theoretically could write it then attempt to immediately read the binary data back into a session but this would be pretty inefficient. 
2. I agree we should have some way for the session manager to purge invalid or corrupt sessions with some error/fatal logging for good measure.

**Comment by AlexKovalevich** [comment]
Thanks for the explanations.
1. Yep, I see, it's org.apache.catalina.session.StandardSession fault and we can't help it.
However StandardSession serialization idea doesn't look safe. Let's try business/dao layers analogy. Usually DAO layer should return exactly what it saved. It shouldn't change the domain/business model it persists. It is pure responsibility of business layer. In this case DAO is tomcat session manager or StandardSession,writeObject method, and service layer or client is MVC controller. If I pass an object to DTO I expect to either receive exactly the same copy later or a notification that something bad has happened. The last thing I want is silent interference of DTO on my business model. 
2. That would be nice to have.

Thank you!

**Comment by shorea** [comment]
1. I 100% agree. Everytime I have to dig into the code for StandardSession I die a little inside. In version 1.0 we actually had a custom serialization scheme but due to some strange side affects in the public interface of StandardSession it caused several bugs. See https://github.com/aws/aws-dynamodb-session-tomcat/pull/19 if you're interested in the backstory for this. I'll ruminate on the issue and see if there is anything we can do to fail faster in this specific scenario.
2. I'll get this and the changes to remove the Converter chain coded up and prepped for release.

**Comment by shorea** [comment]
Opened https://bz.apache.org/bugzilla/show_bug.cgi?id=58284 to see if it can be fixed internally before trying to hack around it.

**Comment by shorea** [comment]
Got an update on the bug report. Proposed solution is to fix what the code is intending to do and skip non-serializable attributes on write and read and log an error. Considering the alternative (throwing exceptions and failing fast) is a breaking change their proposition makes sense. Not ideal as it could hide serious bugs in the users code but it's a little better then writing successfully and dieing on the read. I'll keep this issue open and updated as the bug fix progresses.

**Comment by shorea** [comment]
Just wanted to let you know I haven't forgotten about this. Was out of the office last week and picking this back up. I apologize for the delay.

**Comment by shorea** [comment]
This has been released in https://github.com/aws/aws-dynamodb-session-tomcat/releases/tag/v2.0.1. Also https://bz.apache.org/bugzilla/show_bug.cgi?id=58284 was accepted and is available in Tomcat 7.0.65 and 8.0.27.

**Comment by AlexKovalevich** [comment]
Excellent news! Thank you, Andrew!
