### ISSUE TITLE
All sessions displaying 0 for createdAt or lastUpdatedAt

### ISSUE THREAD

**Issue by mahderc** [aws/aws-dynamodb-session-tomcat#31]
Hello,

Recently I've been trying to figure out how I've managed to get 56,000 items into the DynamoDB table if the Reaper is cleaning up expired sessions every 12 hours.  I noticed that all of the items are displaying 0 for createdAt and lastUpdatedAt.  I'm wondering if this is why the Reaper doesn't appear to be cleaning up expired sessions?

**Comment by shorea** [comment]
If you are using version 2.0 of the session manager those fields aren't actually used and will be removed in a later version (pretty soon per https://github.com/aws/aws-dynamodb-session-tomcat/issues/29). This data is now in the binary attribute sessionData. What's your session expiration set at?

**Comment by mahderc** [comment]
Good to know.  3 days.

**Comment by shorea** [comment]
Is this a production environment? I can suggest some debugging steps but I wouldn't recommend them for a production environment. If it is production adding some debugging to ExpiredSessionsReaper would be a reasonable way to see what the session ids and last accessed time are. I can make this modifications if you're interested in going down that route.

**Comment by shorea** [comment]
Is this still a problem for you?
