### ISSUE TITLE
Empty attributes

### ISSUE THREAD

**Issue by rodri-77** [aws/aws-dynamodb-session-tomcat#32]
I've configured two t2.micro instances behind an ELB with sticky sessions disabled. DynamoDB credentials are ok and sessions are being registered in the DynamoDB table. The same session ID is seen from both nodes, but one of them can't see any attributes.
![node1](https://cloud.githubusercontent.com/assets/14201880/9766876/8e2c1496-571b-11e5-8ea6-c7ce1bff8076.JPG)
![node2](https://cloud.githubusercontent.com/assets/14201880/9766877/8e339c48-571b-11e5-833a-1ea277e6df2c.JPG)

Am I missing any part of configuration?
I'm using version 2.0, and this is context.xml configuration, common in both nodes:

    <WatchedResource>WEB-INF/web.xml</WatchedResource>
    <Manager className="com.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionManager"
             awsAccessKey="<access key>"
             awsSecretKey="<secret key>"
             createIfNotExist="true" />

**Comment by shorea** [comment]
Sorry for the delay in response here. Unfortunately the DynamoDB Session manager currently only supports sticky sessions. See my comments on Issue #23 for details about this.
