### ISSUE TITLE
Outdated version maven repository (1.0.3)

### ISSUE THREAD

**Issue by Raprp** [aws/aws-dynamodb-session-tomcat#33]
Hi,

I've been struggling with problems with the session sync. Only after a lot of time of research I saw that the latest version available on maven repository (1.0.3) was outdated. Version 2.0 fixed the problem.

http://mvnrepository.com/artifact/com.amazonaws/aws-dynamodb-session-tomcat

Maybe it's a good idea to upload the new version to maven repository to avoid new users from getting the old version.

Cheers,

Rafael

**Comment by shorea** [comment]
@Raprp thanks for the suggestion, if we are going to keep the Maven module available we should definitely be updating it. Could you provide some details on how you are using Maven in your application to use the session manager? How do you get the jar picked up by the shared classloader rather than than your context's classloader? Just want to get a better idea of how our Maven customers are consuming this utility so we can provide a better experience.

**Comment by Raprp** [comment]
@shorea My application is running on Elastic Beanstalk and I'm declaring the dependency in maven as:

`<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-dynamodb-session-tomcat</artifactId>
	<version>2.0.0</version>
</dependency>`

And to make the library available to ELB classloader I user the following elastic-beanstalk.config:

container_commands:
  clearLibraries:
    command: rm -rf /usr/share/tomcat7/lib/aws-dynamodb-session-tomcat-\*.jar
    command: rm -rf /usr/share/tomcat7/lib/mysql-connector-java-\*.jar
  mysqlDriver:
    command: cp WEB-INF/lib/mysql-connector-java-\*.jar /usr/share/tomcat7/lib/
  dynamidbSessionManager:
    command: cp WEB-INF/lib/aws-dynamodb-session-tomcat-\*.jar /usr/share/tomcat7/lib/

Please let me know if you see any issue or better approach for this configuration.

**Comment by Raprp** [comment]
I forgot to mention that to use the version 2.0 as a dependency I had to checkout the code from here and install it locally on my maven repository.

**Comment by shorea** [comment]
Thanks for the info @Raprp. I'll make a task to get the latest version published to maven and update this issue when complete.

**Comment by shorea** [comment]
I've got some changes in the works. Planning on updating the maven repo when I publish those changes.

**Comment by shorea** [comment]
This has been released to Maven as version 2.0.1.

http://search.maven.org/#artifactdetails|com.amazonaws|aws-dynamodb-session-tomcat|2.0.1|jar
