### ISSUE TITLE
Any reason why this shouldn't work on Tomcat6?

### ISSUE THREAD

**Issue by twj-developer** [aws/aws-dynamodb-session-tomcat#34]
Long story, but I can't update to Tomcat 7 @ this time. I do want to get session out of the server to support continuous deployment.  This project looks promising, but dropping the 2.0.x release into the tomcat lib directory and adding the following to the tomcat `context.xml `
```
<Manager className="com.amazonaws.services.dynamodb.sessionmanager.DynamoDBSessionManager"
               createIfNotExist="true" />
```
yields the following error:
```
Nov 02, 2015 5:34:09 PM org.apache.catalina.session.PersistentManagerBase start
SEVERE: No Store configured, persistence disabled
```

**Comment by shorea** [comment]
Unfortunately we do rely on a few Tomcat 7 APIs so it is the true minimum.
