### ISSUE TITLE
Maintenance of this project

### ISSUE THREAD

**Issue by grobmeier** [aws/aws-dynamodb-session-tomcat#38]
Hello

there are 3 PRs open and a couple of sometimes very old issues. 

Is this project maintained, apart from updating the SDK?

The question is to fork and deploy to mvn central with another group id or if there are plans to keep this project going. I certainly would appreciate the second one! If there is anything how people can actually help, please advise how the process is.

Thanks!°

Christian

**Comment by shorea** [comment]
@grobmeier The project is still maintained and supported. Last year we did a overhaul of the manager and fixed some serious bugs and released a 2.0 of the product. We don't get a whole lot of traffic to the project so occasionally questions are missed. Are there any features in particular you are looking for the session manager to support?

**Comment by grobmeier** [comment]
@shorea No particular features, just saw a lot of issues were not worked through. It makes me cautious when there are no commits for a while and PRs are not closed. Anyway, since there is somebody watching, I consider using it. Thanks!
