### ISSUE TITLE
session store on the dynamodb but diffrient tomcat diffrient session

### ISSUE THREAD

**Issue by a6091731** [aws/aws-dynamodb-session-tomcat#43]
Hi~

i have store session on the Dynamodb with elastic beanstalk

now i have two instance running

when i go into the pageA and login served by instanceA

than click the button on pageA then go to the pageB served by instanceB

the problem is come -> i need to login again on instanceB

i saw the diffrient session in dynamoDB : Tomcat_SessionState

i think the one is instanceA other is instanceB

can someone tell me

i want to login the webapp on elastic beanstalk

and i login on the webapp whether served by instanceA or instanceB

i just need to login one time , don't login again and again when the serve instance change

can somebody help me?

thank you

**Comment by shorea** [comment]
This session manager implementation requires sticky sessions.
